### ISSUE TITLE
Empty create polluting crates.io

### ISSUE THREAD

**Issue by vincentdephily** [hilbert-space/process#1]
Hi,

looks like you created this crate when experimenting with cargo, that's great :) What's not so great is that this empty crate [still exists on crates.io](https://crates.io/crates/process) and gets regular downloads by confused users, probably due to its very common name.

At the moment it's not possible to delete crates, only prevent them from being newly added as dependencies. As this crate's owner, could do the community a favor and [yank](http://doc.crates.io/crates-io.html#cargo-yank) it from crates.io ? You'll still be able to publish a new release of the crate with useful code if you ever write it. You could also transfer ownership to somebody with a matching project.

Thanks.

**Comment by IvanUkhov** [comment]
Done. Thanks!
