### ISSUE TITLE
Use process name

### ISSUE THREAD

**Issue by otavio** [hilbert-space/process#2]
Hello,

We ended splitting out a crate from our internal source code and we'd like to make it more ergonomic to use over time.

Please see:

https://github.com/otavio/process.rs

**Comment by otavio** [comment]
Never mind. Will go with `process-utils` name.

**Comment by IvanUkhov** [comment]
@otavio, sorry for the late response. Sure! What’s your username on crates.io?

**Comment by otavio** [comment]
otavio.

**Comment by otavio** [comment]
https://crates.io/crates/easy_process

**Comment by IvanUkhov** [comment]
I’m a bit confused. You want to use `easy_process`, `process-utils`, or `process`?

**Comment by IvanUkhov** [comment]
All right. Done! Now it’s all yours!
